spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username:
    password:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
